"""AprendeRL public API."""

from aprenderl.algorithms import (
    A2C,
    C51,
    DDPG,
    DQN,
    FQF,
    IQN,
    PPO,
    QRDQN,
    REINFORCE,
    SAC,
    SARSA,
    TD3,
    TRPO,
    A2CConfig,
    ActorCritic,
    ActorCriticConfig,
    BaseAlgorithm,
    C51Config,
    DDPGConfig,
    DiscreteSAC,
    DiscreteSACConfig,
    DQNConfig,
    FQFConfig,
    IQNConfig,
    OffPolicyAlgorithm,
    OnPolicyAlgorithm,
    PolicyGradientAlgorithm,
    PPOConfig,
    QLearning,
    QLearningConfig,
    QRDQNConfig,
    RainbowDQN,
    RainbowDQNConfig,
    REINFORCEConfig,
    SACConfig,
    SARSAConfig,
    TD3Config,
    TRPOConfig,
)

__all__ = [
    "DDPG",
    "DDPGConfig",
    "TD3",
    "TD3Config",
    "SAC",
    "SACConfig",
    "DiscreteSAC",
    "DiscreteSACConfig",

    "A2C",
    "A2CConfig",
    "ActorCritic",
    "ActorCriticConfig",
    "BaseAlgorithm",
    "C51",
    "C51Config",
    "DQN",
    "DQNConfig",
    "FQF",
    "FQFConfig",
    "IQN",
    "IQNConfig",
    "OffPolicyAlgorithm",
    "OnPolicyAlgorithm",
    "PolicyGradientAlgorithm",
    "PPO",
    "PPOConfig",
    "QLearning",
    "QLearningConfig",
    "REINFORCE",
    "REINFORCEConfig",
    "SARSA",
    "SARSAConfig",
    "TRPO",
    "TRPOConfig",
    "QRDQN",
    "QRDQNConfig",
    "RainbowDQN",
    "RainbowDQNConfig",
]

__version__ = "0.1.0"
